/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pos.store.ui;

import com.pos.store.bao.StoreBAOFactory;
import com.pos.store.bao.warehouse.WarehouseBAO;
import com.pos.store.dto.WareHouseDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author moata
 */
public class WarehouseManage extends javax.swing.JFrame {

    /**
     * Creates new form WarehouseManage
     */
    public WarehouseManage() {
        initComponents();
        initializeDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldFax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jButtonSaveWareH = new javax.swing.JButton();
        jButtonUpdateWareH = new javax.swing.JButton();
        jButtonDeleteWareH = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableWareHouse = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "WareHouse Info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Code");

        jLabel2.setText("Name");

        jLabel3.setText("Phone");

        jLabel4.setText("Fax");

        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });

        jTextFieldFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFaxActionPerformed(evt);
            }
        });

        jLabel5.setText("Address");

        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        jButtonSaveWareH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSaveWareH.setText("Save");
        jButtonSaveWareH.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButtonSaveWareH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveWareHActionPerformed(evt);
            }
        });

        jButtonUpdateWareH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonUpdateWareH.setText("Update");
        jButtonUpdateWareH.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButtonUpdateWareH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateWareHActionPerformed(evt);
            }
        });

        jButtonDeleteWareH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonDeleteWareH.setForeground(new java.awt.Color(204, 0, 0));
        jButtonDeleteWareH.setText("Delete");
        jButtonDeleteWareH.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButtonDeleteWareH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteWareHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonDeleteWareH, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonUpdateWareH, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(jButtonSaveWareH, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(jTextFieldCode))
                        .addGap(140, 140, 140)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveWareH)
                    .addComponent(jButtonUpdateWareH)
                    .addComponent(jButtonDeleteWareH))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Company Wareouses", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTableWareHouse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableWareHouse);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jTextFieldFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFaxActionPerformed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jButtonSaveWareHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveWareHActionPerformed
        // TODO add your handling code here:

        WareHouseDTO theWareHouse = new WareHouseDTO();

        try {

            boolean whIsOk = false;

            if (jTextFieldName.getText().trim().equals("")) {
                theWareHouse.setName(null);                                     // tha's if statement to check if feild null or not
                //JOptionPane.showMessageDialog(this, " Nmae is Empty");
                erroreMassageList.add("Nmae");
                whIsOk = false;
            } else {

                theWareHouse.setName(jTextFieldName.getText());
                whIsOk = true;
            }

            if (jTextFieldAddress.getText().trim().equals("")) {             // tha's if statement to check if feild null or not
                theWareHouse.setAddress(null);
                //JOptionPane.showMessageDialog(this, " Address is Empty");
                erroreMassageList.add("Address");
                whIsOk = false;
            } else {
                theWareHouse.setAddress(jTextFieldAddress.getText());
                whIsOk = true;
            }

            if (jTextFieldPhone.getText().trim().equals("")) {            // tha's if statement to check if feild null or not
                theWareHouse.setPhone(null);
                //JOptionPane.showMessageDialog(this, " Phone is Empty");
                erroreMassageList.add("Phone");
                whIsOk = false;

            } else {

                theWareHouse.setPhone(jTextFieldPhone.getText());
                whIsOk = true;
            }

            if (jTextFieldFax.getText().trim().equals("")) {                    // tha's if statement to check if feild null or not
                theWareHouse.setFax(null);
                //JOptionPane.showMessageDialog(this, " Fax is Empty");
                erroreMassageList.add("Fax");
                whIsOk = false;
            } else {

                theWareHouse.setFax(jTextFieldFax.getText());
                whIsOk = true;
            }
            
            

            if (whIsOk == true) {
                WarehouseBuss.save(theWareHouse);
                JOptionPane.showMessageDialog(this, "The WaeHouse Field has been Saved Successfully. ");
            } else {
                JOptionPane.showMessageDialog(this, "Saving Process Not Complete  ! \n" +erroreMassageList+ " Empty Field(s)\n"+"Try agin." ,"Error", JOptionPane.ERROR_MESSAGE);
            }

            erroreMassageList.removeAll(erroreMassageList);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

    }//GEN-LAST:event_jButtonSaveWareHActionPerformed

    private void jButtonUpdateWareHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateWareHActionPerformed
        // TODO add your handling code here:
        WareHouseDTO theWareHouse = new WareHouseDTO();

        try {
            boolean isOk = false;

            if (jTextFieldCode.getText().trim().equals("")) {
                // tha's if statement to check if feild null or not
                JOptionPane.showMessageDialog(this, " Code is Empty");
                isOk = false;
            } else {

                theWareHouse.setCode(Integer.parseInt(jTextFieldCode.getText()));
                isOk = true;
            }

            if (jTextFieldName.getText().trim().equals("")) {
                theWareHouse.setName(null);                                     // tha's if statement to check if feild null or not
                JOptionPane.showMessageDialog(this, " Nmae is Empty");
            } else {

                theWareHouse.setName(jTextFieldName.getText());
            }

            if (jTextFieldAddress.getText().trim().equals("")) {
                theWareHouse.setAddress(null);
                JOptionPane.showMessageDialog(this, " Address is Empty");        // tha's if statement to check if feild null or not
            } else {
                theWareHouse.setAddress(jTextFieldAddress.getText());
            }

            if (jTextFieldPhone.getText().trim().equals("")) {            // tha's if statement to check if feild null or not
                theWareHouse.setPhone(null);
                JOptionPane.showMessageDialog(this, " Phone is Empty");
            } else {

                theWareHouse.setPhone(jTextFieldPhone.getText());
            }

            if (jTextFieldFax.getText().trim().equals("")) {                    // tha's if statement to check if feild null or not
                theWareHouse.setFax(null);
                JOptionPane.showMessageDialog(this, " Fax is Empty");
            } else {

                theWareHouse.setFax(jTextFieldFax.getText());
            }

            if (isOk == true) {
                WarehouseBuss.save(theWareHouse);
                JOptionPane.showMessageDialog(this, "Item is Updated");
            }
//            else{
//                JOptionPane.showMessageDialog(this, "Code is Impty");
//            }
//            

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }


    }//GEN-LAST:event_jButtonUpdateWareHActionPerformed

    private void jButtonDeleteWareHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteWareHActionPerformed
        // TODO add your handling code here:

        try {

            //allwhs = warehousBusiness.listAll();
//            for (WareHouseDTO wareHouse : AllWareHouses) {
//                if (wareHouse.getCode().equals(jTextFieldCode.getText())) {
//                    WarehouseBuss.delete(wareHouse.getCode());
////                    clearAllData();
////                    getAllData();
//                }
//            }
//            JOptionPane.showMessageDialog(jPanel1, "data deleted successfuly :)");
            WareHouseDTO theWareHouse = new WareHouseDTO();
            boolean isOk = false;

            if (jTextFieldCode.getText().trim().equals("")) {
                // tha's if statement to check if feild null or not
                JOptionPane.showMessageDialog(this, "specify which you want to delete ");
                isOk = false;
            } else {

                theWareHouse.setCode(Integer.parseInt(jTextFieldCode.getText()));
                isOk = true;
            }

            if (isOk == true) {
                WarehouseBuss.delete(theWareHouse.getCode());
                JOptionPane.showMessageDialog(this, "The WareHouse Field with the Code  " + theWareHouse.getCode() + "  has been deleted ");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getClass() + "\n" + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButtonDeleteWareHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarehouseManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarehouseManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarehouseManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarehouseManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarehouseManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteWareH;
    private javax.swing.JButton jButtonSaveWareH;
    private javax.swing.JButton jButtonUpdateWareH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableWareHouse;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldFax;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables

    List<String> erroreMassageList = new ArrayList<>();

    List<WareHouseDTO> AllWareHouses;
    private WarehouseBAO WarehouseBuss = StoreBAOFactory.creatBaoWarehouseImpl();
    private List<WareHouseDTO> WarehouseList = new ArrayList<>();

    static int currntRowIndex;
    static int coltRowIndex;

//    private void initializeDataTabloe(){
//    }
//    
    private void initializeDataTable() {
        try {
            WarehouseList = WarehouseBuss.getAll();
            Object[][] data = null;
            if (WarehouseList != null && !WarehouseList.isEmpty()) {
                data = new Object[WarehouseList.size()][5];
                int row = 0;
                for (WareHouseDTO wh : WarehouseList) {
                    data[row][0] = wh.getCode();
                    data[row][1] = wh.getName();
                    data[row][2] = wh.getPhone();
                    data[row][3] = wh.getFax();
                    data[row++][4] = wh.getAddress();
                }
            }
            jTableWareHouse.setModel(new javax.swing.table.DefaultTableModel(data,
                    new String[]{"code", "Name", "Phone", "Fax", "Address"}));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
